GET http://localhost:8080/todos/17

###

POST http://localhost:8080/todos
Content-Type: application/json
X-Idempotency-Key: 550e8400-e29b-41d4-a716-446655441111

{
  "title": "Redis测试1"
}

###

PUT http://localhost:8080/todos/17
Content-Type: application/json

{
  "id": 17,
  "title": "new"
}

###

DELETE http://localhost:8080/todos/17

###

DELETE http://localhost:8080/todos?ids=2,4,5,9

###
GET http://localhost:8080/todos?pageIndex=1&pageSize=10&sortBy=CREATED_TIME&sortDir=DESC

###
GET http://localhost:8080/todos?pageIndex=1&pageSize=10&sortBy=CREATED_TIME&sortDir=DESC&title=test
Accept: application/json

####
http://localhost:8080/redis/ping

###
GET http://localhost:8080/todos/11


###

# 按 id 查询（测试缓存：连发两次看日志是否只查一次 DB）
GET http://localhost:8080/todos/3

###
POST http://localhost:8080/todos
Content-Type: application/json

{
  "id": 1,
  "title": "写一套 Redis 缓存 Demo"
}

###
DELETE http://localhost:8080/todos/1

###
POST http://localhost:8080/todos
Content-Type: application/json
X-Idempotency-Key: 550e8400-e29b-41d4-a716-446655440000

{
  "title": "Learn1"
}

###
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "title": "Learn optimistic locking (updated)",
  "version": 0
}

###
GET http://localhost:8080/todos/3

###
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "title": "A updated this todo",
  "version": 0
}

###
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "title": "B updated this todo",
  "version": 1
}

### 0. 注册新用户 (初始化数据)
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "test",
  "password": "123"
}

### 1. 登录成功测试 (验证正常逻辑)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "123"
}

### 2. 登录失败测试 (验证全局异常捕获)
# 这里故意填错密码，验证是否返回 "用户名或密码错误" 且格式为 Result JSON
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "wrong_password_888"
}

### 3. 携带 Token 访问受保护接口 (测试 JWT)
GET http://localhost:8080/todos/all
Content-Type: application/json
# 注意：Bearer 后面必须要有一个空格！(这里粘贴登录成功后的token)
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNzY1NzIyNjk2LCJleHAiOjE3NjU4MDkwOTZ9._7lI_sghwcdqGcSuZwOMsZspf-gBrI3wrSx32HYgghA