GET http://localhost:8080/todos/17

###

POST http://localhost:8080/todos
Content-Type: application/json
X-Idempotency-Key: 550e8400-e29b-41d4-a716-446655441111

{
  "title": "Redis测试1"
}

###

PUT http://localhost:8080/todos/17
Content-Type: application/json

{
  "id": 17,
  "title": "new"
}

###

DELETE http://localhost:8080/todos/17

###

DELETE http://localhost:8080/todos?ids=2,4,5,9

###
GET http://localhost:8080/todos?pageIndex=1&pageSize=10&sortBy=CREATED_TIME&sortDir=DESC

###
GET http://localhost:8080/todos?pageIndex=1&pageSize=10&sortBy=CREATED_TIME&sortDir=DESC&title=test
Accept: application/json

####
http://localhost:8080/redis/ping

###
GET http://localhost:8080/todos/1


###

# 按 id 查询（测试缓存：连发两次看日志是否只查一次 DB）
GET http://localhost:8080/todos/3

###
POST http://localhost:8080/todos
Content-Type: application/json

{
  "id": 1,
  "title": "写一套 Redis 缓存 Demo"
}

###
DELETE http://localhost:8080/todos/1

###
POST http://localhost:8080/todos
Content-Type: application/json
X-Idempotency-Key: 550e8400-e29b-41d4-a716-4466554400002
Authorization: Bearer {{accessToken}}

{
  "title": "Learn2"
}

###
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "title": "Learn optimistic locking (updated)",
  "version": 0
}


###
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "title": "A updated this todo",
  "version": 0
}

###
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "title": "B updated this todo",
  "version": 1
}

### 0. 注册新用户 (初始化数据)
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "admin1",
  "password": "123456"
}

### 1. 登录成功测试 (验证正常逻辑)
POST http://localhost:8080/auth/login
Content-Type: application/json
X-Device-Id: {{deviceId}}

{
  "username": "admin1",
  "password": "123456"
}

### 2. 登录失败测试 (验证全局异常捕获)
# 这里故意填错密码，验证是否返回 "用户名或密码错误" 且格式为 Result JSON
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "wrong_password_888"
}

### 3. 携带 Token 访问受保护接口 (测试 JWT)
GET http://localhost:8080/todos/all
Content-Type: application/json
# 注意：Bearer 后面必须要有一个空格！(这里粘贴登录成功后的token)
Authorization: Bearer {{accessToken}}

### 1) Refresh：用 refreshToken 换新 accessToken
@host = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpYXQiOjE3NjY3NzE5NDAsInRva2VuX3R5cGUiOiJhY2Nlc3MiLCJhdXRoIjpbInRvZG86cmVhZCIsInRvZG86d3JpdGUiXSwiZXhwIjoxNzY2NzcyODQwfQ.Rcg1zB403WeDEzaTeaESihPn98JKVyFF4AYUusrQf4U

@refreshToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJqdGkiOiJmYmE1ZjAyOS1jODJjLTRmZTUtOTUxNS05NzVjMmYzYjBjYjIiLCJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImlhdCI6MTc2Njc3MTk0MCwiZXhwIjoxNzY3OTgxNTQwfQ.ML-mJ1-bsaZjguu7sGj1BaWRvba0XtiIvysDASoznnA

@deviceId = 5c7135af-5e5f-46bf-97ae-a419708edb6e

POST {{host}}/auth/refresh
Content-Type: application/json
X-Device-Id: {{deviceId}}

{
  "refreshToken": "{{refreshToken}}"
}

### 2) Logout：撤销 refreshToken（删 Redis refresh:<uuid>）
POST {{host}}/auth/logout
Content-Type: application/json
X-Device-Id: {{deviceId}}

{
  "refreshToken": "{{refreshToken}}"
}

### 热点排行榜
GET {{host}}/todos/top/10
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8080/todos/6
Authorization: Bearer {{accessToken}}
